In [2]:
%pip install pandas
%pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/rafel/.local/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/rafel/.local/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /home/rafel/.local/lib/python3.11/site-packages (from pandas) (2023.4)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy<2,>=1.23.2 in /home/rafel/.local/lib/python3.11/site-packages (from pandas) (1.26.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlrd in /home/rafel/.local/lib/python3.11/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_excel("data_2019.xls")
pd.set_option('display.max_rows', None)

In [5]:
data['d_ini'] = pd.to_datetime(data['d_ini'], format='%d/%m/%Y')
data['d_end'] = pd.to_datetime(data['d_end'], format='%d/%m/%Y')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   d_ini   10 non-null     datetime64[ns]
 1   d_end   10 non-null     datetime64[ns]
 2   kwh     10 non-null     int64
dtypes: datetime64[ns](2), int64(1)
memory usage: 372.0 bytes

In [6]:
data

       d_ini      d_end   kwh
0 2019-01-10 2019-02-13   408
1 2019-02-14 2019-04-14  1116
2 2019-04-15 2019-05-05  1356
3 2019-05-06 2019-06-09  1730
4 2019-06-10 2019-07-11  2102
5 2019-07-12 2019-09-02  2674
6 2019-09-20 2019-09-30  2784
7 2019-10-01 2019-10-31  3144
8 2019-11-01 2019-11-30  3376
9 2019-12-01 2019-12-31  3676

In [7]:
start_date = pd.to_datetime('2019-01-01')
date_range = pd.date_range(start=start_date, end=data['d_end'].max(), freq='D')

In [8]:
daily_data = pd.DataFrame({'Date': date_range})
daily_data['kwh'] = np.nan

In [9]:
for index, row in data.iterrows():
    date_difference = (row['d_end'] - row['d_ini']).days + 1  # +1 para incluir el último día
    kwh_per_day = row['kwh'] / date_difference
    mask = (daily_data['Date'] >= row['d_ini']) & (daily_data['Date'] <= row['d_end'])
    daily_data.loc[mask, 'kwh'] = kwh_per_day

In [10]:
print(daily_data)

          Date         kwh
0   2019-01-01         NaN
1   2019-01-02         NaN
2   2019-01-03         NaN
3   2019-01-04         NaN
4   2019-01-05         NaN
5   2019-01-06         NaN
6   2019-01-07         NaN
7   2019-01-08         NaN
8   2019-01-09         NaN
9   2019-01-10   11.657143
10  2019-01-11   11.657143
11  2019-01-12   11.657143
12  2019-01-13   11.657143
13  2019-01-14   11.657143
14  2019-01-15   11.657143
15  2019-01-16   11.657143
16  2019-01-17   11.657143
17  2019-01-18   11.657143
18  2019-01-19   11.657143
19  2019-01-20   11.657143
20  2019-01-21   11.657143
21  2019-01-22   11.657143
22  2019-01-23   11.657143
23  2019-01-24   11.657143
24  2019-01-25   11.657143
25  2019-01-26   11.657143
26  2019-01-27   11.657143
27  2019-01-28   11.657143
28  2019-01-29   11.657143
29  2019-01-30   11.657143
30  2019-01-31   11.657143
31  2019-02-01   11.657143
32  2019-02-02   11.657143
33  2019-02-03   11.657143
34  2019-02-04   11.657143
35  2019-02-05   11.657143
36  2019-02-06   11.657143
37  2019-02-07   11.657143
38  2019-02-08   11.657143
39  2019-02-09   11.657143
40  2019-02-10   11.657143
41  2019-02-11   11.657143
42  2019-02-12   11.657143
43  2019-02-13   11.657143
44  2019-02-14   18.600000
45  2019-02-15   18.600000
46  2019-02-16   18.600000
47  2019-02-17   18.600000
48  2019-02-18   18.600000
49  2019-02-19   18.600000
50  2019-02-20   18.600000
51  2019-02-21   18.600000
52  2019-02-22   18.600000
53  2019-02-23   18.600000
54  2019-02-24   18.600000
55  2019-02-25   18.600000
56  2019-02-26   18.600000
57  2019-02-27   18.600000
58  2019-02-28   18.600000
59  2019-03-01   18.600000
60  2019-03-02   18.600000
61  2019-03-03   18.600000
62  2019-03-04   18.600000
63  2019-03-05   18.600000
64  2019-03-06   18.600000
65  2019-03-07   18.600000
66  2019-03-08   18.600000
67  2019-03-09   18.600000
68  2019-03-10   18.600000
69  2019-03-11   18.600000
70  2019-03-12   18.600000
71  2019-03-13   18.600000
72  2019-03-14   18.600000
73  2019-03-15   18.600000
74  2019-03-16   18.600000
75  2019-03-17   18.600000
76  2019-03-18   18.600000
77  2019-03-19   18.600000
78  2019-03-20   18.600000
79  2019-03-21   18.600000
80  2019-03-22   18.600000
81  2019-03-23   18.600000
82  2019-03-24   18.600000
83  2019-03-25   18.600000
84  2019-03-26   18.600000
85  2019-03-27   18.600000
86  2019-03-28   18.600000
87  2019-03-29   18.600000
88  2019-03-30   18.600000
89  2019-03-31   18.600000
90  2019-04-01   18.600000
91  2019-04-02   18.600000
92  2019-04-03   18.600000
93  2019-04-04   18.600000
94  2019-04-05   18.600000
95  2019-04-06   18.600000
96  2019-04-07   18.600000
97  2019-04-08   18.600000
98  2019-04-09   18.600000
99  2019-04-10   18.600000
100 2019-04-11   18.600000
101 2019-04-12   18.600000
102 2019-04-13   18.600000
103 2019-04-14   18.600000
104 2019-04-15   64.571429
105 2019-04-16   64.571429
106 2019-04-17   64.571429
107 2019-04-18   64.571429
108 2019-04-19   64.571429
109 2019-04-20   64.571429
110 2019-04-21   64.571429
111 2019-04-22   64.571429
112 2019-04-23   64.571429
113 2019-04-24   64.571429
114 2019-04-25   64.571429
115 2019-04-26   64.571429
116 2019-04-27   64.571429
117 2019-04-28   64.571429
118 2019-04-29   64.571429
119 2019-04-30   64.571429
120 2019-05-01   64.571429
121 2019-05-02   64.571429
122 2019-05-03   64.571429
123 2019-05-04   64.571429
124 2019-05-05   64.571429
125 2019-05-06   49.428571
126 2019-05-07   49.428571
127 2019-05-08   49.428571
128 2019-05-09   49.428571
129 2019-05-10   49.428571
130 2019-05-11   49.428571
131 2019-05-12   49.428571
132 2019-05-13   49.428571
133 2019-05-14   49.428571
134 2019-05-15   49.428571
135 2019-05-16   49.428571
136 2019-05-17   49.428571
137 2019-05-18   49.428571
138 2019-05-19   49.428571
139 2019-05-20   49.428571
140 2019-05-21   49.428571
141 2019-05-22   49.428571
142 2019-05-23   49.428571
143 2019-05-24   49.428571
144 2019-05-25   49.428571
145 2019-05-26   49.428571
146 2019-05-27   49.428571
147 2019-05-28   49.428571
148 2019-05-29   49.428571
149 2019-05-30   49.428571
150 2019-05-31   49.428571
151 2019-06-01   49.428571
152 2019-06-02   49.428571
153 2019-06-03   49.428571
154 2019-06-04   49.428571
155 2019-06-05   49.428571
156 2019-06-06   49.428571
157 2019-06-07   49.428571
158 2019-06-08   49.428571
159 2019-06-09   49.428571
160 2019-06-10   65.687500
161 2019-06-11   65.687500
162 2019-06-12   65.687500
163 2019-06-13   65.687500
164 2019-06-14   65.687500
165 2019-06-15   65.687500
166 2019-06-16   65.687500
167 2019-06-17   65.687500
168 2019-06-18   65.687500
169 2019-06-19   65.687500
170 2019-06-20   65.687500
171 2019-06-21   65.687500
172 2019-06-22   65.687500
173 2019-06-23   65.687500
174 2019-06-24   65.687500
175 2019-06-25   65.687500
176 2019-06-26   65.687500
177 2019-06-27   65.687500
178 2019-06-28   65.687500
179 2019-06-29   65.687500
180 2019-06-30   65.687500
181 2019-07-01   65.687500
182 2019-07-02   65.687500
183 2019-07-03   65.687500
184 2019-07-04   65.687500
185 2019-07-05   65.687500
186 2019-07-06   65.687500
187 2019-07-07   65.687500
188 2019-07-08   65.687500
189 2019-07-09   65.687500
190 2019-07-10   65.687500
191 2019-07-11   65.687500
192 2019-07-12   50.452830
193 2019-07-13   50.452830
194 2019-07-14   50.452830
195 2019-07-15   50.452830
196 2019-07-16   50.452830
197 2019-07-17   50.452830
198 2019-07-18   50.452830
199 2019-07-19   50.452830
200 2019-07-20   50.452830
201 2019-07-21   50.452830
202 2019-07-22   50.452830
203 2019-07-23   50.452830
204 2019-07-24   50.452830
205 2019-07-25   50.452830
206 2019-07-26   50.452830
207 2019-07-27   50.452830
208 2019-07-28   50.452830
209 2019-07-29   50.452830
210 2019-07-30   50.452830
211 2019-07-31   50.452830
212 2019-08-01   50.452830
213 2019-08-02   50.452830
214 2019-08-03   50.452830
215 2019-08-04   50.452830
216 2019-08-05   50.452830
217 2019-08-06   50.452830
218 2019-08-07   50.452830
219 2019-08-08   50.452830
220 2019-08-09   50.452830
221 2019-08-10   50.452830
222 2019-08-11   50.452830
223 2019-08-12   50.452830
224 2019-08-13   50.452830
225 2019-08-14   50.452830
226 2019-08-15   50.452830
227 2019-08-16   50.452830
228 2019-08-17   50.452830
229 2019-08-18   50.452830
230 2019-08-19   50.452830
231 2019-08-20   50.452830
232 2019-08-21   50.452830
233 2019-08-22   50.452830
234 2019-08-23   50.452830
235 2019-08-24   50.452830
236 2019-08-25   50.452830
237 2019-08-26   50.452830
238 2019-08-27   50.452830
239 2019-08-28   50.452830
240 2019-08-29   50.452830
241 2019-08-30   50.452830
242 2019-08-31   50.452830
243 2019-09-01   50.452830
244 2019-09-02   50.452830
245 2019-09-03         NaN
246 2019-09-04         NaN
247 2019-09-05         NaN
248 2019-09-06         NaN
249 2019-09-07         NaN
250 2019-09-08         NaN
251 2019-09-09         NaN
252 2019-09-10         NaN
253 2019-09-11         NaN
254 2019-09-12         NaN
255 2019-09-13         NaN
256 2019-09-14         NaN
257 2019-09-15         NaN
258 2019-09-16         NaN
259 2019-09-17         NaN
260 2019-09-18         NaN
261 2019-09-19         NaN
262 2019-09-20  253.090909
263 2019-09-21  253.090909
264 2019-09-22  253.090909
265 2019-09-23  253.090909
266 2019-09-24  253.090909
267 2019-09-25  253.090909
268 2019-09-26  253.090909
269 2019-09-27  253.090909
270 2019-09-28  253.090909
271 2019-09-29  253.090909
272 2019-09-30  253.090909
273 2019-10-01  101.419355
274 2019-10-02  101.419355
275 2019-10-03  101.419355
276 2019-10-04  101.419355
277 2019-10-05  101.419355
278 2019-10-06  101.419355
279 2019-10-07  101.419355
280 2019-10-08  101.419355
281 2019-10-09  101.419355
282 2019-10-10  101.419355
283 2019-10-11  101.419355
284 2019-10-12  101.419355
285 2019-10-13  101.419355
286 2019-10-14  101.419355
287 2019-10-15  101.419355
288 2019-10-16  101.419355
289 2019-10-17  101.419355
290 2019-10-18  101.419355
291 2019-10-19  101.419355
292 2019-10-20  101.419355
293 2019-10-21  101.419355
294 2019-10-22  101.419355
295 2019-10-23  101.419355
296 2019-10-24  101.419355
297 2019-10-25  101.419355
298 2019-10-26  101.419355
299 2019-10-27  101.419355
300 2019-10-28  101.419355
301 2019-10-29  101.419355
302 2019-10-30  101.419355
303 2019-10-31  101.419355
304 2019-11-01  112.533333
305 2019-11-02  112.533333
306 2019-11-03  112.533333
307 2019-11-04  112.533333
308 2019-11-05  112.533333
309 2019-11-06  112.533333
310 2019-11-07  112.533333
311 2019-11-08  112.533333
312 2019-11-09  112.533333
313 2019-11-10  112.533333
314 2019-11-11  112.533333
315 2019-11-12  112.533333
316 2019-11-13  112.533333
317 2019-11-14  112.533333
318 2019-11-15  112.533333
319 2019-11-16  112.533333
320 2019-11-17  112.533333
321 2019-11-18  112.533333
322 2019-11-19  112.533333
323 2019-11-20  112.533333
324 2019-11-21  112.533333
325 2019-11-22  112.533333
326 2019-11-23  112.533333
327 2019-11-24  112.533333
328 2019-11-25  112.533333
329 2019-11-26  112.533333
330 2019-11-27  112.533333
331 2019-11-28  112.533333
332 2019-11-29  112.533333
333 2019-11-30  112.533333
334 2019-12-01  118.580645
335 2019-12-02  118.580645
336 2019-12-03  118.580645
337 2019-12-04  118.580645
338 2019-12-05  118.580645
339 2019-12-06  118.580645
340 2019-12-07  118.580645
341 2019-12-08  118.580645
342 2019-12-09  118.580645
343 2019-12-10  118.580645
344 2019-12-11  118.580645
345 2019-12-12  118.580645
346 2019-12-13  118.580645
347 2019-12-14  118.580645
348 2019-12-15  118.580645
349 2019-12-16  118.580645
350 2019-12-17  118.580645
351 2019-12-18  118.580645
352 2019-12-19  118.580645
353 2019-12-20  118.580645
354 2019-12-21  118.580645
355 2019-12-22  118.580645
356 2019-12-23  118.580645
357 2019-12-24  118.580645
358 2019-12-25  118.580645
359 2019-12-26  118.580645
360 2019-12-27  118.580645
361 2019-12-28  118.580645
362 2019-12-29  118.580645
363 2019-12-30  118.580645
364 2019-12-31  118.580645

In [11]:
daily_data.to_csv('daily_data.csv', index=False)